modLoader="javafml"
loaderVersion="[47,)"
license="Custom license"

[[mods]]
modId="ejr"
version="0.0.4-beta"
displayName="Epic Journey:Reforged"
displayURL="https://github.com/CJiangqiu/EpicJourneyReforged"
logoFile="logo.png"
credits="Anthor:CJiangqiu,Mascot:Mcreator"
authors="CJiangqiu"
description="An epic journey in another world."
[[dependencies.ejr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.ejr]]
modId="epic_core_api"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"
[[dependencies.ejr]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ejr]]
    modId="jade"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ejr]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ejr]]
    modId="geckolib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ejr]]
    modId="playeranimator"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ejr]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

